include: "/models/backend/config.model"
include: "/views/**/*.view"
include: "/explores/stock/*"
include: "/explores/distribution/*"
include: "/explores/range/supplier_funding_model.explore"
include: "/explores/stock/stock_cover.explore"
include: "/views/prod/department_specific/supply_chain/stocklocation.view.lkml"
label: "Stock"
